# -*- coding: utf-8 -*-
"""WKDM_v9_2_sumit_4gaussian_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OMaJHHMjY8nSw6hvpOCU5iN-ZxklPvr

### Start
"""

!pip install dm-haiku

import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
from functools import partial
import haiku as hk
import optax

# --- Params ---
N = 4096 # number of initial samples per target
steps = 128
T_tot = 1.0 # total time
D = 0.05 # diffusion constant, ref 0.1
guidance_strength = 2.0
L = 5.0
beta = 0.1  # risk control, ref 0.1

lr = 1e-3
total_epochs = 1501
key = jax.random.PRNGKey(0)

"""### utils"""

# --- Initialize ---
def init_sample(k, N, means=[(2.0, 0.0), (0.0, 2.0), (0.0, -2.0), (-2.0, 0.0)], std=0.2):
    keys = jax.random.split(k, 4)
    N_per_cluster = N // 4
    clusters = []
    for i in range(4):
        samples = jax.random.normal(keys[i], (N_per_cluster, 2)) * std + jnp.array(means[i])
        clusters.append(samples)
    return jnp.concatenate(clusters, axis=0)


# ---two moon---
# def init_sample(key, N, noise=0.1):
#     N_half = N // 2
#     theta1 = jnp.linspace(0, jnp.pi, N_half)
#     theta2 = jnp.linspace(0, jnp.pi, N_half)

#     # First moon (upper)
#     x1 = jnp.stack([2.0 * jnp.cos(theta1), 2.0 * jnp.sin(theta1) + 1.0], axis=1)

#     # Second moon (lower, offset and flipped)
#     x2 = jnp.stack([2.0 - 2.0 * jnp.cos(theta2), -2.0 * jnp.sin(theta2) - 1.0], axis=1)

#     data = jnp.concatenate([x1, x2], axis=0)

#     # Add Gaussian noise
#     noise_key = jax.random.split(key, 1)[0]
#     data += noise * jax.random.normal(noise_key, data.shape)

#     return data


# ---swiss roll---
# def init_sample(key, N, noise=0.05):
#     t = jax.random.uniform(key, shape=(N,), minval= jnp.pi, maxval= 5.5 * jnp.pi)

#     x = 0.2 * t * jnp.cos(t)
#     y = 0.2 * t * jnp.sin(t)

#     data = jnp.stack([x, y], axis=1)

#     # Add Gaussian noise
#     noise_key = jax.random.split(key, 1)[0]
#     data += noise * jax.random.normal(noise_key, data.shape)

#     return data

def compute_grad(params, x, idx, mlp):
    # x: (N, 2)

    def single_forward(x_single, idx_single):
        x_single = x_single[None, :]               # (1,2)
        w_single = mlp.apply(params, x_single, idx_single) # idx_single should be (1,)
        return w_single.squeeze()                # scalar

    # grad_fn = jax.vmap(jax.grad(single_forward), in_axes=0)
    # idx_expanded = jnp.full((x.shape[0],), idx)
    # grads = grad_fn(x, idx_expanded)  # x is (N, 2)

    grad_fn = jax.vmap(jax.grad(single_forward), in_axes=(0, None))
    grads = grad_fn(x, idx)  # x is (N, 2)
    return grads

"""### model"""

# --- w network ---
# def w_net_fn(hidden_dim=64, num_layers=5, num_steps=100):
#     # PE
#     class PosEmbed(hk.Module):
#         def __init__(self, num_steps, dim, name=None):
#             super().__init__(name=name)
#             self.num_steps = num_steps
#             self.dim = dim

#         def __call__(self, positions):  # positions: (N,)
#             embed_table = hk.get_parameter("pos_embed", [self.num_steps, self.dim],
#                                            init=hk.initializers.TruncatedNormal(stddev=0.02))
#             return embed_table[positions]  # (N, dim)

#     # network
#     def net_fn(x, step_expanded):  # x: (N, d), step_expanded: (N, )

#         x_embed = hk.nets.MLP([hidden_dim, hidden_dim])(x)
#         step_embed = PosEmbed(num_steps=num_steps, dim=hidden_dim)(step_expanded)
#         h = x_embed + step_embed

#         for _ in range(num_layers):
#             h = hk.Linear(hidden_dim)(h)
#             h = jax.nn.gelu(h)
#             # h = jax.nn.relu(h)
#         w = hk.Linear(1)(h)
#         return w

#     return net_fn

# def w_net_fn(hidden_dim=64, num_layers=10, num_steps=100):
#     # Sinusoidal embedding for discrete time steps
#     def sinusoidal_embedding(step_ids, dim):
#         # step_ids: (N,)
#         step_ids = step_ids.astype(jnp.float32)[:, None]  # (N, 1)
#         freqs = jnp.exp(-jnp.arange(0, dim, 2) * (jnp.log(10000.0) / dim))  # (dim/2,)
#         angles = step_ids * freqs  # (N, dim/2)
#         emb = jnp.concatenate([jnp.sin(angles), jnp.cos(angles)], axis=-1)  # (N, dim)
#         return emb

#     # network
#     def net_fn(x, step_expanded):  # x: (N, d), step_expanded: (N,)
#         x_embed = hk.nets.MLP([hidden_dim, hidden_dim])(x)
#         step_embed = sinusoidal_embedding(step_expanded, hidden_dim)

#         h = x_embed + step_embed  # Inject time early

#         for _ in range(num_layers):
#             h = hk.Linear(hidden_dim)(h)
#             h = jax.nn.gelu(h)
#             h += step_embed  # Inject time deeply

#         w = hk.Linear(1)(h)
#         return w

#     return net_fn

def w_net_fn(hidden_dim=64, num_layers=8, num_steps=100):
    # PE
    class PosEmbed(hk.Module):
        def __init__(self, num_steps, dim, name=None):
            super().__init__(name=name)
            self.num_steps = num_steps
            self.dim = dim

        def __call__(self, positions):  # positions: (N,)
            embed_table = hk.get_parameter("pos_embed", [self.num_steps, self.dim],
                                           init=hk.initializers.TruncatedNormal(stddev=0.02))
            return embed_table[positions]  # (N, dim)

    # network
    def net_fn(x,step_expanded):

        x_embed = hk.nets.MLP([hidden_dim, hidden_dim])(x)
        step_embed = PosEmbed(num_steps=num_steps, dim=hidden_dim)(step_expanded)
        h = x_embed + step_embed

        for _ in range(num_layers):
            shortcut = h
            h = hk.Linear(hidden_dim)(h)
            h = jax.nn.gelu(h)
            h = hk.Linear(hidden_dim)(h)
            # h = hk.LayerNorm(axis=-1, create_scale=True, create_offset=True)(h)

            if shortcut.shape[-1] != hidden_dim:
                shortcut = hk.Linear(hidden_dim)(shortcut)
            h = h + shortcut

        # output layer
        h = hk.Linear(1)(h)
        return h

    return net_fn


# --- nu network ---
def nu_net_fn(hidden_dim=128, num_layers=10):
    def nu_net(x):
        h = x
        for _ in range(num_layers):
            h = hk.Linear(hidden_dim)(h)
            h = jax.nn.gelu(h)
        h = hk.Linear(1)(h)  # Output a scalar
        nu = 1.0 + 0.5 * jax.nn.tanh(h)
        return nu

    return nu_net


# class LearnablePositionalEncoding(hk.Module):
#     def __init__(self, seq_len, dim, name=None):
#         super().__init__(name=name)
#         self.seq_len = seq_len
#         self.dim = dim

#     def __call__(self):
#         pos_embed = hk.get_parameter("pos_embed", shape=[self.seq_len, self.dim],
#                                      init=hk.initializers.RandomNormal(stddev=0.02))
#         return pos_embed  # shape (seq_len, dim)


# def w_net_fn(hidden_dim=128, num_layers=10):
#     def net_fn(x,t_expanded):
#         # h = jnp.concatenate([x, t_expanded], axis=-1)
#         # t_emb = hk.nets.MLP([hidden_dim, x.shape[-1]])(t_expanded)
#         t_embed = hk.nets.MLP([hidden_dim, hidden_dim])(time_embedding(t_expanded, hidden_dim))
#         x_embed = hk.nets.MLP([hidden_dim, hidden_dim])(x)
#         h = x_embed + t_embed
#         for _ in range(num_layers):
#             h = hk.Linear(hidden_dim)(h)
#             h = jax.nn.gelu(h)
#         w = hk.Linear(1)(h)  # Output a scalar
#         return w

#     return net_fn

"""### step function"""

# --- Step function ---
def step(pos, target_pos, guidance_strength, key, w_params, nu_params,
         step_idx, dt,
         step_mode, train_mode):

    # get w
    step_idx_expanded = jnp.full((pos.shape[0],), step_idx)
    w = w_net.apply(w_params, pos, step_idx_expanded)

    # get nu
    if train_mode == "pretraining":
        nu = jnp.ones_like(w)
    elif train_mode == "finetuning":
        nu = nu_net.apply(nu_params, pos)
    else:
        raise ValueError("Invalid train_mode")

    # Noise
    key, subkey = jax.random.split(key)
    noise = jax.random.normal(subkey, (N,2)) * jnp.sqrt(2 * D * dt)

    # OUP
    guidance_vec = target_pos - pos

    # step
    if step_mode == "focusing": # from xT to x0
        dpos = dt * guidance_strength * guidance_vec + noise

    elif step_mode == "reversing": # from x0 to xT

        # gradient
        grad_w = compute_grad(w_params, pos, step_idx, w_net)
        dpos = grad_w * dt - dt * guidance_strength * guidance_vec + noise

        # # Normalize gradient
        # grad_norm = jnp.linalg.norm(grad_w, axis=-1, keepdims=True) + 1e-8
        # drift_direction = grad_w / grad_norm

        # # Mask drift where gradient norm is small
        # epsilon = 1e-3
        # drift_mask = (grad_norm > epsilon).astype(jnp.float32)
        # drift = 10.0 * drift_direction * drift_mask * dt
        # dpos = - drift + noise

        # if train_mode == "pretraining":
        #     pass
        # elif train_mode == "finetuning":
        #     dpos = dpos/nu
        # else:
        #     raise ValueError("Invalid train_mode")

    else:
        raise ValueError("Invalid step_mode")

    # update position
    pos_new = pos + dpos
    # pos_new = jnp.mod(pos + dpos + L, 2.0 * L) - L # periodic boundary

    return pos_new, key, w, nu

"""### FK loss"""

@jax.jit
def loss_fk(w_params, nu_params, trajectory, step_idx_vec, dt_vec, beta):

    steps, batch_size, _ = trajectory.shape

    # --- Prepare time-space points ---
    x_k = trajectory[:-1]  # (steps-1, batch, 2)
    x_kp1 = trajectory[1:]  # (steps-1, batch, 2)
    dx = x_kp1 - x_k # (steps-1, batch, 2)
    s_k = step_idx_vec[:-1][:, None].repeat(batch_size, axis=1)  # (steps-1, batch)
    dt_k = dt_vec[:-1][:, None].repeat(batch_size, axis=1)  # (steps-1, batch)

    # xk_s = jnp.concatenate([x_k, s_k[..., None]], axis=-1)  # (steps-1, batch, 3)
    # xk_s_flat = xk_s.reshape(-1, 3)
    xk_flat = x_k.reshape(-1, 2)
    s_k_flat = s_k.reshape(-1)
    dt_k_flat = dt_k.reshape(-1)

    # Terminal points
    x_1 = trajectory[-1]  # (batch, 2)
    # s_1 = jnp.full((batch_size, 1), s_values[-1])
    # x1_s = jnp.concatenate([x_1, s_1], axis=-1)

    # --- Evaluate Z ---
    W_k = w_net.apply(w_params, xk_flat, s_k_flat)
    Z_k = jnp.exp(beta * W_k).squeeze()  # (steps-1) * batch

    #
    # W_1 = w_net.apply(w_params, x_1)
    # Z_1 = jnp.exp(beta * W_1).squeeze()       # batch
    # Z_1_repeated = jnp.tile(Z_1, reps=(steps - 1,)) # Broadcast Z_1 to match Z_k

    #
    x_0 = trajectory[0]
    # x_0_repeated = jnp.tile(x_0, reps=(steps - 1,)) # Broadcast x_0 to match x_k
    x_0_repeated = jnp.repeat(x_0, steps - 1, axis=0)
    x_0_repeated_flat = x_0_repeated.reshape(-1, 2)
    # W_0_repeated = w_net.apply(w_params, x_0_repeated_flat, s_k_flat)
    W_0_repeated = w_net.apply(w_params, x_0_repeated_flat, jnp.zeros_like(s_k_flat))
    Z_0_repeated = jnp.exp(beta * W_0_repeated).squeeze()       # batch
    # Z_0_repeated = jnp.tile(Z_0, reps=(steps - 1,)) # Broadcast Z_0 to match Z_k

    # print(x_0_repeated_flat.shape)
    # print(s_k_flat.shape)
    # print(W_0_repeated.shape)

    # --- Evaluate nu ---
    if nu_params is None:
        nu_k = jnp.ones((xk_flat.shape[0],))
    else:
        nu_k = nu_net.apply(nu_params, xk_flat).squeeze()

    # --- Compute path costs ---
    # s_k_flat = s_k.reshape(-1)
    # cost = nu_k * (1.0 - s_k_flat)  # General nu
    cost_single = nu_k * dt_k_flat
    cost_single = cost_single.reshape(steps-1, batch_size)
    cost = - beta * jnp.cumsum(cost_single, axis = 0)
    cost_flat = cost.reshape(-1)

    # penalty
    x_mid = 0.5 * (x_k + x_kp1)
    p1_single = guidance_strength * (x_mid * dx).sum(axis=-1)
    p1 = (1.0/2.0 * D) * jnp.cumsum(p1_single, axis = 0)
    p1_flat = p1.reshape(-1)

    p2_single = guidance_strength ** 2 * (x_mid ** 2 * dt_k[...,None]).sum(axis=-1)
    p2 = - (1.0/4.0 * D) * jnp.cumsum(p2_single, axis = 0)
    p2_flat = p2.reshape(-1)

    # --- FK target ---
    # target = jnp.exp(beta * cost) * Z_1_repeated
    # target = jnp.exp(cost_flat + p1_flat + p2_flat) * Z_0_repeated
    target = jnp.exp(cost_flat) * Z_0_repeated

    # --- Squared loss ---
    loss_per_point = (Z_k - target) ** 2
    fk_loss = jnp.mean(loss_per_point)

    return fk_loss

"""### FK loss local"""

@jax.jit
def loss_fk_local(w_params, nu_params, trajectory, step_idx_vec, dt_vec, beta):

    steps, batch_size, _ = trajectory.shape

    # Get pairs (x_k, s_k) and (x_{k+1}, s_{k+1})
    x_k = trajectory[:-1]            # shape (steps - 1, batch, 2)
    x_kp1 = trajectory[1:]          # shape (steps - 1, batch, 2)

    s_k = step_idx_vec[:-1][:, None].repeat(batch_size, axis=1)  # (steps-1, batch)
    s_kp1 = step_idx_vec[1:][:, None].repeat(batch_size, axis=1)
    dt_k = dt_vec[:-1][:, None].repeat(batch_size, axis=1)
    dt_kp1 = dt_vec[1:][:, None].repeat(batch_size, axis=1)

    # Stack spatial and time dimensions
    # xk_s = jnp.concatenate([x_k, s_k[..., None]], axis=-1)       # (steps-1, batch, 3)
    # xkp1_s = jnp.concatenate([x_kp1, s_kp1[..., None]], axis=-1) # (steps-1, batch, 3)

    # Flatten for batch evaluation
    # xk_s_flat = xk_s.reshape(-1, 3)
    # xkp1_s_flat = xkp1_s.reshape(-1, 3)
    xk_flat = x_k.reshape(-1, 2)
    xkp1_flat = x_kp1.reshape(-1, 2)
    s_k_flat = s_k.reshape(-1)
    s_kp1_flat = s_kp1.reshape(-1)
    dt_k_flat = dt_k.reshape(-1)
    dt_kp1_flat = dt_kp1.reshape(-1)

    # Evaluate Z and nu
    W_k = w_net.apply(w_params, xk_flat, s_k_flat)
    Z_k = jnp.exp(beta * W_k).squeeze()
    W_kp1 = w_net.apply(w_params, xkp1_flat, s_kp1_flat)
    Z_kp1 = jnp.exp(beta * W_kp1).squeeze()


    if nu_params is None:
        nu_k = jnp.ones((xk_flat.shape[0],))
    else:
        nu_k = nu_net.apply(nu_params, xk_flat).squeeze()

    #
    cost = beta * nu_k * dt_k_flat

    dx = x_kp1 - x_k
    x_mid = 0.5 * (x_k + x_kp1)
    dt_mid = 0.5 * (dt_k + dt_kp1)
    p1_single = - (1.0/2.0 * D) * guidance_strength * (x_mid * dx).sum(axis=-1)
    p1_single_flat = p1_single.reshape(-1)

    p2_single = (1.0/4.0 * D) * guidance_strength ** 2 * (x_mid ** 2 * dt_mid[...,None]).sum(axis=-1)
    p2_single_flat = p2_single.reshape(-1)

    # Compute FK local loss vectorized
    target = jnp.exp(cost + p1_single_flat + p2_single_flat) * Z_kp1

    # Squared error
    loss_per_point = (Z_k - target) ** 2

    # Average over all (steps - 1) * batch samples
    fk_local_loss = jnp.mean(loss_per_point)

    return fk_local_loss

"""### total loss"""

def forward_loss_fn(w_params, pos0, key, target_pos, steps, T_tot, guidance_strength, step_mode, train_mode):
    subkey1, subkey2 = jax.random.split(key)

    # rollout the trajectory
    step_idx_vec, dt_vec, traj, traj_w, traj_nu = rollout(pos0, subkey1, w_params, None, guidance_strength, steps, T_tot, step_mode, train_mode)

    final_pos = traj[-1]
    w_0 = traj_w[0]
    w_T = traj_w[-1]

    # dual loss
    # loss1 = jnp.mean(w_0) - jnp.mean(w_T) # default
    loss1 = 1e-1 * (jnp.mean(w_T) - jnp.mean(w_0)) + jnp.mean((w_0-10.0)**2)
    # loss1 = - jnp.mean(w_0) + (jnp.mean(w_T) + 1.0) ** 2.0

    # FK losses
    loss2 = loss_fk(w_params, None, traj, step_idx_vec, dt_vec, beta)
    loss3 = loss_fk_local(w_params, None, traj, step_idx_vec, dt_vec, beta)

    # negative sampling
    pos_ns = jax.random.uniform(subkey2, shape=traj.shape, minval=-5.0, maxval=5.0).reshape(-1, 2)

    # regularize w
    step_ns = jnp.arange(steps)[:,None].repeat(traj.shape[1], axis=1).reshape(-1)
    w_ns = w_net.apply(w_params, pos_ns, step_ns)
    penalty1 = jnp.mean(w_ns ** 2)

    # weights regularization
    # l2 = sum([jnp.sum(jnp.square(p)) for p in jax.tree_util.tree_leaves(w_params)])

    # total loss
    # loss = 1e-2 * loss1 + loss2 + loss3 + 0.1 * penalty1 # default
    loss = 1e-2 * loss1 + loss2 + 0.1 * penalty1

    return loss.squeeze(), (loss1.squeeze(), loss2.squeeze(), loss3.squeeze(), final_pos, traj)

# #
# def loss_fn(w_params, nu_params, pos0, key, target_pos, steps, dt, guidance_strength, step_mode, train_mode):
#     subkey1, subkey2 = jax.random.split(key)

#     # rollout the trajectory
#     step_idx_vec, traj, traj_w, traj_nu = rollout(pos0, subkey1, w_params, nu_params, steps, dt, step_mode, train_mode)

#     final_pos = traj[-1]
#     w_0 = traj_w[0]
#     w_T = traj_w[-1]

#     # dual loss
#     loss1 = jnp.mean(w_0) - jnp.mean(w_T)

#     # FK losses
#     if train_mode == "pretraining":
#         loss2 = loss_fk(w_params, None, traj, step_idx_vec, dt, beta)
#         loss3 = loss_fk_local(w_params, None, traj, step_idx_vec, dt, beta)
#     elif train_mode == "finetuning":
#         loss2 = loss_fk(w_params, nu_params, traj, step_idx_vec, dt, beta)
#         loss3 = loss_fk_local(w_params, nu_params, traj, step_idx_vec, dt, beta)
#     else:
#         raise ValueError("Invalid train_mode")

#     # negative sampling
#     pos_ns = jax.random.uniform(subkey2, shape=traj.shape, minval=-5.0, maxval=5.0).reshape(-1, 2)

#     # regularize w
#     step_ns = jnp.arange(steps)[:,None].repeat(traj.shape[1], axis=1).reshape(-1, 1)
#     w_ns = w_net.apply(w_params, pos_ns, step_ns)
#     penalty1 = 0.5 * jnp.mean(w_ns ** 2)

#     # regularize nu
#     nu_ns = nu_net.apply(nu_params, pos_ns)
#     penalty2 = 1e-2 * jnp.mean(traj_nu**2) + 1e-2 * jnp.mean((1 - nu_ns)**2)

#     # total loss
#     if step_mode == "focusing":
#         loss = 0.1 * loss1 + loss2 + loss3 + penalty1 + penalty2
#     elif step_mode == "reversing":
#         loss = penalty2
#     else:
#         raise ValueError("Invalid step_mode")

#     return loss.squeeze(), (loss1.squeeze(), loss2.squeeze(), loss3.squeeze(), final_pos, traj)

"""### rollout"""

# --- Single Rollout ---
@partial(jax.jit, static_argnums=(4,5,6,7,8,9,10))
def rollout(pos0, key, w_params, nu_params, guidance_strength, steps, T_tot, step_mode, train_mode, target_pos=jnp.zeros((1,2)), steps_beyond_horizon = 0):
    def body(state, inputs):
        step_idx, dt = inputs
        pos, key = state
        new_pos, new_key, w, nu = step(pos, target_pos, guidance_strength, key, w_params, nu_params, step_idx, dt, step_mode, train_mode)
        return (new_pos, new_key), (new_pos, w, nu)

    init_state = (pos0, key)
    step_idx_vec = jnp.arange(steps)
    # weights = (step_idx_vec + 1) ** 0.5
    weights = jnp.ones_like(step_idx_vec)
    dt_vec = weights / jnp.sum(weights) * T_tot

    if step_mode == "focusing":
        pass

    elif step_mode == "reversing":
        step_idx_vec = jnp.flip(step_idx_vec[:-1])
        dt_vec = jnp.flip(dt_vec[:-1])
        # generative step beyond horizon
        if steps_beyond_horizon > 0:
            last_step = step_idx_vec[-1]
            last_dt = dt_vec[-1]
            step_idx_vec = jnp.concatenate([step_idx_vec, jnp.repeat(last_step, steps_beyond_horizon)])
            dt_vec = jnp.concatenate([dt_vec, jnp.repeat(last_dt, steps_beyond_horizon)])

    else:
        raise ValueError("Invalid step_mode")

    scan_inputs = (step_idx_vec, dt_vec)
    (_, _), (traj, traj_w, traj_nu) = jax.lax.scan(body, init_state, scan_inputs)

    return step_idx_vec, dt_vec, traj, traj_w, traj_nu

"""### train step"""

@partial(jax.jit, static_argnums=(2,3,7))
def train_step(w_params, w_opt_state, steps, T_tot, pos0, key, target_pos, guidance_strength):
    (loss, (loss1, loss2, loss3, final_pos, traj)), grads = jax.value_and_grad(forward_loss_fn, has_aux=True)(
        w_params, pos0, key, target_pos, steps, T_tot, guidance_strength, step_mode="focusing", train_mode="pretraining")

    w_updates, w_opt_state = w_opt.update(grads, w_opt_state)
    w_params = optax.apply_updates(w_params, w_updates)

    return w_params, w_opt_state, loss, loss1, loss2, loss3, final_pos, traj

# @jax.jit
# def fine_tune_step(w_params, nu_params, w_opt_state, nu_opt_state, pos0, key, target_pos, guidance_strength):
#     (loss, (loss1, loss2, loss3, final_pos, traj)), grads = jax.value_and_grad(loss_fn, argnums=(0, 1), has_aux=True)(
#         w_params, nu_params, pos0, key, target_pos, steps, dt, guidance_strength, step_mode="reversing", train_mode="finetuning")

#     w_updates, w_opt_state = w_opt.update(grads[0], w_opt_state)
#     w_params = optax.apply_updates(w_params, w_updates)
#     nu_updates, nu_opt_state = nu_opt.update(grads[1], nu_opt_state)
#     nu_params = optax.apply_updates(nu_params, nu_updates)

#     return w_params, nu_params, w_opt_state, nu_opt_state, loss, loss1, loss2, loss3, final_pos, traj

"""### **MAIN RUN**"""

# ---------------
#      Main
# ---------------

# --- model ---
# mlp = hk.without_apply_rng(hk.transform(control_mlp_fn()))
# params = mlp.init(jax.random.PRNGKey(42), jnp.zeros((N, 2)), 0.0) # last argument is t

w_net = hk.without_apply_rng(hk.transform(w_net_fn()))
key, subkey = jax.random.split(key)
w_params = w_net.init(subkey, jnp.zeros((N, 2)), jnp.full((N,), 0, dtype=jnp.int32))

# --- optimizer ---
w_opt = optax.adam(lr)
w_opt_state = w_opt.init(w_params)

# --- Pre-Train ---
loss_lst = []
target_pos = jnp.zeros((1,2))

for epoch in range(total_epochs):

    # Initialization
    key, subkey1, subkey2 = jax.random.split(key, 3)
    pos0 = init_sample(subkey1, N)

    # train
    w_params, w_opt_state, loss, loss1, loss2, loss3, final_pos, _ = train_step(w_params, w_opt_state, steps, T_tot, pos0, subkey2, target_pos, guidance_strength)

    loss_lst.append(loss)

    if epoch % 50 == 0:

        print(f"Epoch {epoch}, Loss: {loss:.6f}, Loss1: {loss1:.6f}, Loss2: {loss2:.6f}, Loss3: {loss3:.6f}")

        # plot
        fig, axs = plt.subplots(1, 3, figsize=(12, 4))

        axs[0].scatter(final_pos[:, 0], final_pos[:, 1], s=1, c='red', label='Final')
        axs[0].scatter(target_pos[:, 0], target_pos[:, 1], s=1, c='black', label='Target')
        axs[0].scatter(pos0[:, 0], pos0[:, 1], s=1, c='blue', label='Initial')
        axs[0].set_title("Final Configuration")
        axs[0].legend()
        axs[0].set_xlim(-L, L)
        axs[0].set_ylim(-L, L)
        axs[0].set_aspect('equal')

        axs[1].plot(jnp.array(loss_lst)/jnp.max(jnp.array(loss_lst)))
        axs[1].set_xlabel("Epoch")
        axs[1].set_ylabel("Loss")
        axs[1].set_title("Training Loss")

        # visualize MLP
        resolution = 100
        x = jnp.linspace(-L, L, resolution)
        y = jnp.linspace(-L, L, resolution)
        xx, yy = jnp.meshgrid(x, y)
        grid_points = jnp.stack([xx.ravel(), yy.ravel()], axis=-1)  # (resolution^2, 2)

        s_array = jnp.full((grid_points.shape[0], ), 0)
        w = w_net.apply(w_params, grid_points, s_array)  # (resolution^2, 1)

        w = w.reshape((resolution, resolution))  # reshape for plotting
        pc = axs[2].pcolormesh(xx, yy, w, shading='auto', cmap='viridis')
        plt.colorbar(pc, ax=axs[2])
        axs[2].set_title("Value function, w(s=0)")
        axs[2].set_xlabel("x")
        axs[2].set_ylabel("y")
        axs[2].set_xlim(-L, L)
        axs[2].set_ylim(-L, L)
        axs[2].set_aspect('equal')

        plt.tight_layout()
        plt.show()



# nu_net = hk.without_apply_rng(hk.transform(nu_net_fn()))
# key, subkey = jax.random.split(key)
# nu_params = nu_net.init(subkey, jnp.zeros((N, 2)))
# nu_opt = optax.adam(1e-4)
# nu_opt_state = nu_opt.init(nu_params)

"""### Visualization"""

import matplotlib.animation as animation
from IPython.display import HTML

# Subsample s values to avoid too many frames
s_values_vis = jnp.arange(steps)
resolution = 100

# Precompute W for each s (since computing during animation would be slow)
W_frames = []
x = jnp.linspace(-L, L, resolution)
y = jnp.linspace(-L, L, resolution)
xx, yy = jnp.meshgrid(x, y)
grid_points = jnp.stack([xx.ravel(), yy.ravel()], axis=-1)

for s in s_values_vis:
    s_array = jnp.full((grid_points.shape[0],), s)

    W_vals = w_net.apply(w_params, grid_points, s_array)  # (resolution^2, 1), t is dummy

    W_vals = W_vals.squeeze()
    W_frames.append(W_vals.reshape((resolution, resolution)))

# ---- Animation ----
fig, ax = plt.subplots(figsize=(4, 4))
# pc = ax.pcolormesh(xx, yy, W_frames[0], shading='auto', cmap='viridis', vmax=0.0, vmin=-2.0)
pc = ax.pcolormesh(xx, yy, W_frames[0], shading='auto', cmap='viridis')
cbar = plt.colorbar(pc, ax=ax)
title = ax.set_title("W(x, step={:.2f})".format(float(s_values_vis[0])))
ax.set_aspect('equal')

def update(frame):
    pc.set_array(W_frames[frame].ravel())  # Flatten the 2D array for pcolormesh
    title.set_text("W(x, step={:.2f})".format(float(s_values_vis[frame])))
    return pc,

ani = animation.FuncAnimation(
    fig, update, frames=len(s_values_vis), interval=500
)

# ani.save(f'W_field.mp4', writer='ffmpeg', fps=25, dpi=150)
ani.save(f'W_field.gif', writer='pillow', fps=25, dpi=150)
plt.close()

# Display as HTML in Colab
HTML(ani.to_jshtml())





from IPython.display import HTML
import matplotlib.animation as animation

def make_video(key1, key2, steps, T_tot, N, step_mode="focusing", steps_beyond_horizon = 0):

    # generating starting points
    if step_mode == "focusing":
        pos0_viz = init_sample(key1, N)

    elif step_mode == "reversing":
        std = 0.25
        pos0_viz = jax.random.normal(key1, (N, 2)) * std

    else:
        raise ValueError("Invalid step_mode")

    # rollout the trajectory
    _, _, trajectory, _, _ = rollout(pos0_viz, key2, w_params, None, guidance_strength, steps, T_tot, step_mode=step_mode, train_mode="pretraining", steps_beyond_horizon = steps_beyond_horizon)

    # Setup figure
    fig, ax = plt.subplots(figsize=(4, 4))
    pos_init = trajectory[0]

    scat_points = ax.scatter(pos_init[:, 0], pos_init[:, 1], color='red', s=1)

    ax.set_xlim(-L, L)
    ax.set_ylim(-L, L)
    ax.set_aspect('equal')
    ax.set_title(f'{step_mode}')
    plt.show()

    def update(frame):
        pos = trajectory[frame]
        scat_points.set_offsets(pos)
        return (scat_points, )

    ani = animation.FuncAnimation(fig, update, frames=trajectory.shape[0] - 1, interval=40, blit=True)
    # ani.save(f'{step_mode}.mp4', writer='ffmpeg', fps=25, dpi=150)
    ani.save(f'{step_mode}.gif', writer='pillow', fps=25, dpi=150)
    return ani

key, subkey1, subkey2 = jax.random.split(key,3)
ani = make_video(subkey1, subkey2, steps, T_tot, N, step_mode="focusing")
HTML(ani.to_jshtml())

key, subkey1, subkey2 = jax.random.split(key,3)
ani = make_video(subkey1, subkey2, steps, T_tot, N, step_mode="reversing", steps_beyond_horizon=0)
HTML(ani.to_jshtml())



"""### Figures"""

from mpl_toolkits.axes_grid1.inset_locator import inset_axes
import matplotlib.pyplot as plt

def save_combined_snapshots(key1, key2, steps, T_tot, N):
    resolution = 100

    s_indices_W = [steps - 1, steps // 2, 1]     # for W snapshots
    s_indices_p = [0, steps // 2, steps - 1]     # for point clouds
    norm_times = [0.0, 0.5, 1.0]                 # time labels for both

    x = jnp.linspace(-L, L, resolution)
    y = jnp.linspace(-L, L, resolution)
    xx, yy = jnp.meshgrid(x, y)
    grid_points = jnp.stack([xx.ravel(), yy.ravel()], axis=-1)

    # --- W field snapshots ---
    W_snapshots = []
    for s in s_indices_W:
        s_array = jnp.full((grid_points.shape[0],), s)
        W_vals = w_net.apply(w_params, grid_points, s_array).squeeze()
        W_snapshots.append(W_vals.reshape((resolution, resolution)))

    # --- Trajectory snapshots ---
    std = 0.25
    pos0_viz = jax.random.normal(key1, (N, 2)) * std

    _, _, trajectory, _, _ = rollout(
        pos0_viz,
        key2,
        w_params,
        None,
        guidance_strength,
        steps,
        T_tot,
        step_mode="reversing",
        train_mode="pretraining"
    )

    # --- Plot: 3 rows × 2 columns (W left, Particles right) ---
    fig, axs = plt.subplots(3, 2, figsize=(8, 12), sharex=True, sharey=True)

    # Global W scale
    vmin = min([w.min() for w in W_snapshots])
    vmax = max([w.max() for w in W_snapshots])

    for i, (W, s_idx, t_norm) in enumerate(zip(W_snapshots, s_indices_W, norm_times)):
        # Left column: W(x,t)
        pc = axs[i, 0].pcolormesh(
            xx, yy, W, shading='nearest', cmap='viridis', vmin=vmin, vmax=vmax
        )
        axs[i, 0].set_title(f"W(x, t={t_norm:.2f})", fontsize=12, pad=6)
        axs[i, 0].set_aspect('equal')

        # Right column: particles
        pos = trajectory[s_indices_p[i]]
        axs[i, 1].scatter(pos[:, 0], pos[:, 1], color='red', s=1)
        axs[i, 1].set_title(f"Particles at t={t_norm:.2f})", fontsize=12, pad=6)
        axs[i, 1].set_xlim(-L, L)
        axs[i, 1].set_ylim(-L, L)
        axs[i, 1].set_aspect('equal')

    # Inset colorbar inside the bottom-left plot
    ax_cb = inset_axes(axs[2, 0], width="5%", height="60%", loc="lower left", borderpad=2)
    cbar = fig.colorbar(pc, cax=ax_cb, orientation='vertical')
    cbar.ax.tick_params(labelsize=10, colors='white')

    # 🔧 Manual control: reduce space between columns
    plt.subplots_adjust(wspace=0.05, hspace=0.1, left=0.05, right=0.95, top=0.95, bottom=0.05)

    plt.savefig("combined_snapshots_3x2.png", dpi=300)
    plt.show()
    plt.close()

# Example usage
key = jax.random.PRNGKey(0)
key1, key2 = jax.random.split(key)
save_combined_snapshots(key1, key2, steps, T_tot, N)