# -*- coding: utf-8 -*-
"""WKDM_v12_3_image_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHyy2TwaXbt8JG6cjaW1mUa42f6dHAGs

Note:
"""

#@title initialization
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import functools
from torch.optim import Adam
from torch.utils.data import DataLoader, Subset
import torchvision.transforms as transforms
import tqdm
from torchvision.datasets import MNIST
from torchvision.utils import make_grid

import matplotlib.pyplot as plt


device = 'cuda'
theta = 5.0
D = 0.01
beta = 0.1
n_epochs = 200
batch_size =  1024
num_steps = 100
lr = 1e-4
sample_batch_size = 16

transform = transforms.Compose([transforms.ToTensor(), transforms.Lambda(lambda x: x * 2. - 1.)])

dataset = MNIST('.', train=True, transform=transform, download=True)

# Filter indices where label == 1
# indices = torch.where(torch.tensor(dataset.targets) == 1)[0]
# subset = Subset(dataset, indices)

data_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=4)

# Show a few images
x, y = next(iter(data_loader))

plt.figure(figsize=(10, 2))
for i in range(10):
    plt.subplot(1, 10, i + 1)
    plt.imshow(x[i].squeeze(), cmap='gray')
    plt.axis('off')
    plt.title(f"Label: {y[i].item()}")
plt.show()

#@title model

import torch.nn.functional as F

class GaussianFourierProjection(nn.Module):
    def __init__(self, embed_dim, scale=30.):
        super().__init__()
        self.W = nn.Parameter(torch.randn(embed_dim // 2) * scale, requires_grad=False)

    def forward(self, x):  # x: (B,)
        x_proj = x[:, None] * self.W[None, :] * 2 * np.pi  # (B, D/2)
        return torch.cat([torch.sin(x_proj), torch.cos(x_proj)], dim=-1)  # (B, D)

class Dense(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.dense = nn.Linear(input_dim, output_dim)

    def forward(self, x):  # x: (B, embed_dim)
        return self.dense(x)[..., None, None]  # (B, C, 1, 1) for broadcasting

# class ScoreNet(nn.Module):
#     def __init__(self, channels=[128, 256, 256, 128], embed_dim=128):
#         super().__init__()
#         self.embed = nn.Sequential(
#             GaussianFourierProjection(embed_dim=embed_dim),
#             nn.Linear(embed_dim, embed_dim)
#         )

#         self.conv1 = nn.Conv2d(1, channels[0], kernel_size=3, stride=1, padding=1, bias=False)
#         self.dense1 = Dense(embed_dim, channels[0])
#         self.gnorm1 = nn.GroupNorm(4, num_channels=channels[0])

#         self.conv2 = nn.Conv2d(channels[0], channels[1], kernel_size=3, stride=2, padding=1, bias=False)
#         self.dense2 = Dense(embed_dim, channels[1])
#         self.gnorm2 = nn.GroupNorm(4, num_channels=channels[1])

#         self.conv3 = nn.Conv2d(channels[1], channels[2], kernel_size=3, stride=2, padding=1, bias=False)
#         self.dense3 = Dense(embed_dim, channels[2])
#         self.gnorm3 = nn.GroupNorm(4, num_channels=channels[2])

#         self.conv4 = nn.Conv2d(channels[2], channels[3], kernel_size=3, stride=2, padding=1, bias=False)
#         self.dense4 = Dense(embed_dim, channels[3])
#         self.gnorm4 = nn.GroupNorm(4, num_channels=channels[3])

#         self.final_fc = nn.Linear(channels[3], 1)
#         self.act = nn.ReLU()

#     def forward(self, x, t):
#         embed = self.act(self.embed(t))  # (B, embed_dim)

#         h1 = self.conv1(x) + self.dense1(embed)
#         h1 = self.act(self.gnorm1(h1))

#         h2 = self.conv2(h1) + self.dense2(embed)
#         h2 = self.act(self.gnorm2(h2))

#         h3 = self.conv3(h2) + self.dense3(embed)
#         h3 = self.act(self.gnorm3(h3))

#         h4 = self.conv4(h3) + self.dense4(embed)
#         h4 = self.act(self.gnorm4(h4))

#         h = h4.mean(dim=(2, 3))        # Global average pooling → (B, C)
#         out = self.final_fc(h)         # → (B, 1)

#         # out = F.sigmoid(out)

#         return out.squeeze(-1)         # → (B,)

class ScoreNet(nn.Module):
  """A time-dependent score-based model built upon U-Net architecture."""

  def __init__(self, channels=[32, 64, 128, 256], embed_dim=256):
    """Initialize a time-dependent score-based network.

    Args:
      marginal_prob_std: A function that takes time t and gives the standard
        deviation of the perturbation kernel p_{0t}(x(t) | x(0)).
      channels: The number of channels for feature maps of each resolution.
      embed_dim: The dimensionality of Gaussian random feature embeddings.
    """
    super().__init__()
    # Gaussian random feature embedding layer for time
    self.embed = nn.Sequential(GaussianFourierProjection(embed_dim=embed_dim),
         nn.Linear(embed_dim, embed_dim))
    # Encoding layers where the resolution decreases
    self.conv1 = nn.Conv2d(1, channels[0], 3, stride=1, bias=False)
    self.dense1 = Dense(embed_dim, channels[0])
    self.gnorm1 = nn.GroupNorm(4, num_channels=channels[0])
    self.conv2 = nn.Conv2d(channels[0], channels[1], 3, stride=2, bias=False)
    self.dense2 = Dense(embed_dim, channels[1])
    self.gnorm2 = nn.GroupNorm(32, num_channels=channels[1])
    self.conv3 = nn.Conv2d(channels[1], channels[2], 3, stride=2, bias=False)
    self.dense3 = Dense(embed_dim, channels[2])
    self.gnorm3 = nn.GroupNorm(32, num_channels=channels[2])
    self.conv4 = nn.Conv2d(channels[2], channels[3], 3, stride=2, bias=False)
    self.dense4 = Dense(embed_dim, channels[3])
    self.gnorm4 = nn.GroupNorm(32, num_channels=channels[3])

    # Decoding layers where the resolution increases
    self.tconv4 = nn.ConvTranspose2d(channels[3], channels[2], 3, stride=2, bias=False)
    self.dense5 = Dense(embed_dim, channels[2])
    self.tgnorm4 = nn.GroupNorm(32, num_channels=channels[2])
    self.tconv3 = nn.ConvTranspose2d(channels[2] + channels[2], channels[1], 3, stride=2, bias=False, output_padding=1)
    self.dense6 = Dense(embed_dim, channels[1])
    self.tgnorm3 = nn.GroupNorm(32, num_channels=channels[1])
    self.tconv2 = nn.ConvTranspose2d(channels[1] + channels[1], channels[0], 3, stride=2, bias=False, output_padding=1)
    self.dense7 = Dense(embed_dim, channels[0])
    self.tgnorm2 = nn.GroupNorm(32, num_channels=channels[0])
    self.tconv1 = nn.ConvTranspose2d(channels[0] + channels[0], 1, 3, stride=1)

    # The swish activation function
    self.act = lambda x: x * torch.sigmoid(x)
    # self.marginal_prob_std = marginal_prob_std

  def forward(self, x, t):
    # Obtain the Gaussian random feature embedding for t
    embed = self.act(self.embed(t))
    # Encoding path
    h1 = self.conv1(x)
    ## Incorporate information from t
    h1 += self.dense1(embed)
    ## Group normalization
    h1 = self.gnorm1(h1)
    h1 = self.act(h1)
    h2 = self.conv2(h1)
    h2 += self.dense2(embed)
    h2 = self.gnorm2(h2)
    h2 = self.act(h2)
    h3 = self.conv3(h2)
    h3 += self.dense3(embed)
    h3 = self.gnorm3(h3)
    h3 = self.act(h3)
    h4 = self.conv4(h3)
    h4 += self.dense4(embed)
    h4 = self.gnorm4(h4)
    h4 = self.act(h4)

    # Decoding path
    h = self.tconv4(h4)
    ## Skip connection from the encoding path
    h += self.dense5(embed)
    h = self.tgnorm4(h)
    h = self.act(h)
    h = self.tconv3(torch.cat([h, h3], dim=1))
    h += self.dense6(embed)
    h = self.tgnorm3(h)
    h = self.act(h)
    h = self.tconv2(torch.cat([h, h2], dim=1))
    h += self.dense7(embed)
    h = self.tgnorm2(h)
    h = self.act(h)
    h = self.tconv1(torch.cat([h, h1], dim=1))

    h = h.mean(dim=(2, 3))

    # Normalize output
    # h = h / self.marginal_prob_std(t)[:, None, None, None]
    return h.squeeze(-1)

#@title Loss

# --- OU sampling ---
def OU_sample(x, t):
    device = x.device
    t_batched = torch.ones(x.shape[0], device=device) * t
    exp_term = torch.exp(-theta * t_batched).view(-1, 1, 1, 1)
    mean = exp_term * x
    var = (D / theta) * (1. - exp_term**2)
    std = torch.sqrt(var).view(-1, 1, 1, 1)

    # Sample from OU conditional
    noise = torch.randn_like(x)
    x_t = mean + std * noise  # OU sample
    return x_t


def spatial_smoothness(w, kernel_size=3):
    pad = kernel_size // 2
    grad_x = w[:, :, :, 1:] - w[:, :, :, :-1]
    grad_y = w[:, :, 1:, :] - w[:, :, :-1, :]
    return (grad_x**2).mean() + (grad_y**2).mean()


# --- loss fk ---
def loss_fn_single_time(model, x, t, beta, theta, D, eps=1e-5):

    batch_size = x.shape[0]
    device = x.device

    # Sample random times t ~ Uniform(eps, 1)
    random_t = torch.rand(batch_size, device=device) * (1. - eps) + eps
    random_t_neg = torch.rand(batch_size, device=device) * (1. - eps) + eps

    # Compute OU mean and std
    exp_term = torch.exp(-theta * random_t).view(-1, 1, 1, 1)
    mean = exp_term * x
    var = (D / theta) * (1. - exp_term**2)
    std = torch.sqrt(var).view(-1, 1, 1, 1)

    # Sample from OU conditional
    noise = torch.randn_like(x)
    x_t = mean + std * noise  # OU sample

    # Evaluate model outputs
    w = model(x_t, random_t)
    z = torch.exp(beta * w)

    w0 = model(x, torch.zeros_like(random_t))
    z0 = torch.exp(beta * w0)

    # w1 = model(torch.sqrt(D / theta).view(-1, 1, 1, 1) * noise, torch.ones_like(random_t))
    # z1 = torch.exp(beta * w1)

    # Feynman-Kac loss (target from x0 at t=0)
    target = torch.exp(- beta * random_t) * z0
    loss_fk = (z - target) ** 2

    # Optional dual loss
    loss_dual = (z0 - 1.0)**2

    # Negative sampling
    w_neg = model(x_t, random_t_neg)
    z_neg = torch.exp(beta * w_neg)
    loss_neg = (z_neg - 0.1)**2

    # Spatial loss
    spatial_loss = spatial_smoothness(x_t)  # w_img_batch has shape (B, 1, H, W)

    total_loss = 1e0 * loss_fk + 1e0 * loss_dual + 1e-3 * spatial_loss + 1e-1 * loss_neg
    return total_loss.mean(), loss_fk.mean(), loss_dual.mean()



#@title generative

# --- generative ---
def grad_w_fn(model, x, t):

    x = x.detach().requires_grad_(True)
    t = t.detach()

    output = model(x, t)  # shape (B,)
    grad_w = torch.autograd.grad(
        outputs=output.sum(), inputs=x,
        create_graph=True, retain_graph=True, only_inputs=True
    )[0]

    return grad_w

def Euler_Maruyama_sampler_ou(score_model, theta, D, batch_size, num_steps, device='cuda'):
    # Time steps: from s=1 → s=eps (reverse)
    # time_steps = torch.linspace(1., eps, num_steps, device=device)
    time_steps = torch.linspace(1.0, 0.0, steps=num_steps + 2, device=device)[1:-1]
    step_size = time_steps[0] - time_steps[1]

    # Initialize from N(0, D / theta)
    stationary_std = (D / theta) ** 0.5
    x = torch.randn(batch_size, 1, 28, 28, device=device) * stationary_std
    init_x = x.clone()

    score_model.eval()
    for s in time_steps:
        batch_t = torch.ones(batch_size, device=device) * s
        grad_w = grad_w_fn(score_model, x, batch_t)  # ∇W(x,s)

        drift = theta * x + grad_w  # OU drift + learned correction
        noise = torch.randn_like(x) * (2 * D * step_size) ** 0.5

        x = x + step_size * drift + noise

        # convert to original range

    return x, init_x

def OU_forward_validate(model, x0, T=1.0, dt=0.01):

    with torch.no_grad():
        num_steps = int(T / dt)
        x = x0.clone()

        w_0 = model(x, torch.zeros(x.shape[0])).detach().cpu()
        traj_w = [w_0]

        for step in range(num_steps):
            noise = torch.randn_like(x)
            drift = -theta * x * dt
            diffusion = torch.sqrt(torch.tensor(2 * D * dt, device=x.device)) * noise
            x = x + drift + diffusion

            t_batched = torch.ones(x.shape[0], device=device) * step * dt
            w = model(x, t_batched).detach().cpu()

            traj_w.append(w)

        #
        traj_w = torch.stack(traj_w, dim=1)
        traj_w = traj_w.view(traj_w.shape[0], traj_w.shape[1], -1)

    return traj_w  # return final state and full trajectory

def show_bump(model, x0, T=1.0, dt=0.01):
    model.eval()
    num_steps = int(T / dt)
    times = torch.linspace(0, T, num_steps + 1, device=x0.device)
    x = x0.clone()
    traj = [x0.clone()]

    # rollout traj
    for _ in range(num_steps):
        noise = torch.randn_like(x)
        drift = -theta * x * dt
        diffusion = torch.sqrt(torch.tensor(2 * D * dt, device=x.device)) * noise
        x = x + drift + diffusion
        traj.append(x.clone())

    traj = torch.stack(traj)  # [T+1, B, ...]
    B = traj.shape[1]
    traj = traj.permute(1, 0, *range(2, traj[0].ndim + 1))

    #
    with torch.no_grad():
        for ind in [1,10]:
            x = traj[ind]
            for t in times[::11]:
                t_batched = torch.ones(x.shape[0], device=device) * t

                w = model(x, t_batched).detach().cpu()  # shape [T+1, 1] or [T+1]

                # Plot
                plt.plot(times.cpu(), w, label=f's={t:.2f}')

            plt.xlabel("Arc length", fontsize = 14)
            plt.ylabel("w", fontsize = 14)
            # plt.title("w vs Arc length")
            # plt.legend(fontsize=12)
            plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5), fontsize=12)
            plt.grid(True)
            plt.show()



#@title define the model
score_model = torch.nn.DataParallel(ScoreNet())
score_model = score_model.to(device)
optimizer = Adam(score_model.parameters(), lr=lr)

# show trajectories
traj_w = OU_forward_validate(score_model, x, T=1.0, dt=0.01)

plt.figure(figsize=(10, 5))
for i in range(traj_w.shape[0]):
    plt.plot(traj_w[i])
plt.title('Trajectory of w')
plt.xlabel('Forward time step')
plt.show()

# show bump
show_bump(score_model, x, T=1.0, dt=0.01)

#@title Training

#
# time_steps = torch.linspace(0.0, 1.0, steps=num_steps + 2, device=device)[1:-1]
loss_lst =[]
loss_fk_lst = []
loss_dual_lst = []

for epoch in range(n_epochs):
    avg_loss = 0.
    avg_loss_fk = 0.
    avg_loss_dual = 0.
    num_items = 0

    # train
    for x, y in data_loader:
        x = x.to(device)

        # sample a random time
        # t_idx = torch.randint(0, len(time_steps), (1,))
        # t = time_steps[t_idx]
        t = torch.rand(1, device=device)

        # loss and backprop
        loss, loss_fk, loss_dual = loss_fn_single_time(score_model, x, t, beta, theta, D)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        #
        avg_loss += loss.item() * x.shape[0]
        avg_loss_fk += loss_fk.item() * x.shape[0]
        avg_loss_dual += loss_dual.item() * x.shape[0]
        num_items += x.shape[0]

    print(f'epoch {epoch}, loss {avg_loss / num_items}, loss_fk {avg_loss_fk / num_items}, loss_dual {avg_loss_dual / num_items}')

    loss_lst.append(avg_loss / num_items)
    loss_fk_lst.append(avg_loss_fk / num_items)
    loss_dual_lst.append(avg_loss_dual / num_items)


    if epoch%10 == 0:
        # Sampling
        samples, samples_init = Euler_Maruyama_sampler_ou(
            score_model, theta=theta, D=D,
            batch_size=sample_batch_size, num_steps=num_steps, device=device
        )

        # plot loss curves
        fig, ax = plt.subplots(1, 3, figsize=(15, 5))
        ax[0].plot(torch.tensor(loss_lst)/torch.max(torch.tensor(loss_lst)))
        ax[0].set_title('loss')
        ax[1].plot(loss_fk_lst)
        ax[1].set_title('loss_fk')
        ax[2].plot(loss_dual_lst)
        ax[2].set_title('loss_dual')
        plt.show()

        # plot w trajectories
        traj_w = OU_forward_validate(score_model, x, T=1.0, dt=0.01)

        plt.figure(figsize=(10, 5))
        for i in range(traj_w.shape[0]):
            plt.plot(traj_w[i])
        plt.title('Trajectory of w')
        plt.xlabel('Forward time step')
        plt.show()

        #
        show_bump(score_model, x, T=1.0, dt=0.01)

        # Visualization
        samples = samples.clamp(-1.0, 1.0)  # if trained on [-1, 1]
        samples = (samples + 1.0) / 2.0  # Maps [-1, 1] → [0, 1]
        sample_grid = make_grid(samples, nrow=int(np.sqrt(sample_batch_size)))
        plt.figure(figsize=(6, 6))
        plt.axis('off')
        plt.imshow(sample_grid.permute(1, 2, 0).cpu(), vmin=0., vmax=1.)
        plt.title("Generated samples")
        plt.show()

        # samples_init = samples_init.clamp(-1.0, 1.0)
        # samples_init = (samples_init + 1.0) / 2.0  # Maps [-1, 1] → [0, 1]
        # sample_grid_2 = make_grid(samples_init, nrow=int(np.sqrt(sample_batch_size)))
        # plt.figure(figsize=(6, 6))
        # plt.axis('off')
        # plt.imshow(sample_grid_2.permute(1, 2, 0).cpu(), vmin=0., vmax=1.)
        # plt.title("Initial samples")
        # plt.show()

        torch.save(score_model.state_dict(), 'ckpt.pth')



#@title TSNE

import torch
import torchvision.transforms as transforms
from torchvision.datasets import MNIST
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np

# --- Load and prepare real MNIST data ---
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Lambda(lambda x: x * 2. - 1.)  # Normalize to [-1, 1]
])
mnist = MNIST('.', train=True, download=True, transform=transform)
loader = torch.utils.data.DataLoader(mnist, batch_size=1000, shuffle=True)
real_data, real_labels = next(iter(loader))
real_data = real_data.view(real_data.size(0), -1).detach().cpu()  # Flatten and detach

# --- Prepare generated samples ---
fake_data = samples.detach().view(samples.size(0), -1).cpu()  # Flatten and detach
fake_data_init = samples_init.detach().view(samples_init.size(0), -1).cpu()  # Flatten and detach

# --- Run t-SNE ---
all_data = torch.cat([real_data, fake_data, fake_data_init], dim=0).numpy()
tsne = TSNE(n_components=2, perplexity=30, init='pca', random_state=42)
embeddings = tsne.fit_transform(all_data)

# --- Split embeddings ---
real_emb = embeddings[:real_data.size(0)]
fake_emb = embeddings[real_data.size(0):real_data.size(0)+fake_data.size(0)]
fake_emb_init = embeddings[real_data.size(0)+fake_data.size(0):]



# --- Plot with digit labels ---
plt.figure(figsize=(10, 8))

# Color real digits by class (0–9)
for digit in range(10):
    idx = (real_labels == digit).numpy()
    plt.scatter(real_emb[idx, 0], real_emb[idx, 1], s=10, alpha=0.5, label=f'Digit {digit}')

# Plot generated data in black
plt.scatter(fake_emb[:, 0], fake_emb[:, 1], s=10, c='black', alpha=0.5, label='Generated')
plt.scatter(fake_emb_init[:, 0], fake_emb_init[:, 1], s=10, c='green', alpha=0.9, label='Initial')

plt.title('t-SNE: Real MNIST Digits (Colored by Class) vs Generated Samples')
plt.xlabel('t-SNE Dimension 1')
plt.ylabel('t-SNE Dimension 2')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

#@title Create generation video

import torch
import numpy as np
import matplotlib.pyplot as plt
from torchvision.utils import make_grid
from IPython.display import HTML
import matplotlib.animation as animation


def create_video(score_model, theta, D, batch_size, num_steps, device='cuda'):
    time_steps = torch.linspace(1.0, 0.0, steps=num_steps + 2, device=device)[1:-1]
    step_size = time_steps[0] - time_steps[1]

    # Initialize from N(0, D / theta)
    stationary_std = (D / theta) ** 0.5
    x = torch.randn(batch_size, 1, 28, 28, device=device) * stationary_std
    frames = []  # Store frames for the video

    for i, s in enumerate(time_steps):
        batch_t = torch.ones(batch_size, device=device) * s
        grad_w = grad_w_fn(score_model, x, batch_t)  # ∇W(x,s)

        drift = theta * x + grad_w  # OU drift + learned correction
        noise = torch.randn_like(x) * (2 * D * step_size) ** 0.5

        x = x + step_size * drift + noise

        # conver to orignal range
        samples = x
        samples = samples.clamp(-1.0, 1.0)
        samples = (samples + 1.0)/2

        # Save current frame
        if i%10 == 0:
          grid = make_grid(samples, nrow=int(np.sqrt(batch_size)))
          img = grid.permute(1, 2, 0).cpu().numpy()
          frames.append(img)

    # Plot animation
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.axis('off')
    im = ax.imshow(frames[0], vmin=0., vmax=1.)

    def update(i):
        im.set_data(frames[i])
        return [im]

    ani = animation.FuncAnimation(fig, update, frames=len(frames), interval=50, blit=True)
    plt.close(fig)  # Prevent static image display
    return ani

ani = create_video(score_model, theta, D, batch_size=16, num_steps=100, device='cuda')
HTML(ani.to_jshtml())

#@title Run forward and reverse
def run_forward_reverse(score_model, x, ind, theta, D, device='cuda'):

    # get one image from data list
    img = x[100].squeeze().cpu()
    plt.imshow(img, cmap='gray')
    plt.show()

    # calculate terminal mean and std
    # exp_term = torch.exp(torch.tensor(-1.0)).view(1, 1, 1, 1).cpu()
    # mean = exp_term * img
    # var = D/theta * (1. - exp_term**2)
    # std = torch.sqrt(var).view(1, 1, 1, 1)

    exp_term = torch.exp(-theta * torch.tensor(1.0)).view(-1, 1, 1, 1).cpu()
    mean = exp_term * img
    var = (D / theta) * (1. - exp_term**2)
    std = torch.sqrt(var).view(-1, 1, 1, 1)

    # sample one image
    noise = torch.randn_like(img)
    img = mean + std * noise

    plt.imshow(img.squeeze(), cmap='gray')
    plt.show()

    #
    x = img
    frames = []  # Store frames for the video

    time_steps = torch.linspace(1e-5, 1., 200, device=device)
    step_size = time_steps[1] - time_steps[0]
    for i, s in enumerate(time_steps):
        batch_t = torch.ones(1, device=device) * s
        grad_w = grad_w_fn(score_model, x, batch_t)  # ∇W(x,s)

        drift = theta * x + 1.0 * grad_w  # OU drift + learned correction
        noise = torch.randn_like(x) * ((2 * D * step_size) ** 0.5).cpu()

        x = x + step_size.cpu() * drift.cpu() + noise

        # conver to orignal range
        samples = x
        samples = samples.clamp(-1.0, 1.0)
        samples = (samples + 1.0)/2

        # Save current frame
        if i%10 == 0:
          # grid = make_grid(samples, nrow=int(np.sqrt(batch_size)))
          # img = grid.permute(1, 2, 0).cpu().numpy()
          frames.append(samples.squeeze(0,1).detach().cpu().numpy())


    # Plot animation
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.axis('off')
    im = ax.imshow(frames[0], vmin=0., vmax=1.)

    def update(i):
        im.set_data(frames[i])
        return [im]

    ani = animation.FuncAnimation(fig, update, frames=len(frames), interval=50, blit=True)
    plt.close(fig)  # Prevent static image display
    return ani


# Show a few images
x, y = next(iter(data_loader))
ani = run_forward_reverse(score_model, x, 100, theta=2.5, D=D, device='cuda')
HTML(ani.to_jshtml())

